/** Convert a zero-based column index to an Excel column letter (`0 → "A"`, `25 → "Z"`, `26 → "AA"`). */

export type { RangeRef } from '@ascend/core'
export { indexToColumn, parseA1, parseRange, toA1 } from '@ascend/core'
export type {
	XlsxPackageContentTypeDefault,
	XlsxPackageContentTypeOverride,
	XlsxPackageContentTypeSource,
	XlsxPackageGraph,
	XlsxPackageGraphPart,
	XlsxPackageGraphRelationship,
	XlsxPackageLossPolicy,
	XlsxPackageOwnerScope,
} from '@ascend/io-xlsx'
export type { AgentDocEntry, AgentDocKind, AgentDocSearchResult } from './agent-docs.ts'
export { loadAgentDocs, readAgentDoc, searchAgentDocs } from './agent-docs.ts'
export type {
	AgentCommitOptions,
	AgentCommitPackageActionProofOptions,
	AgentCommitResult,
	AgentModelOutput,
	AgentPlanResult,
	AgentPostWriteVerification,
	AgentTraceArtifact,
	AgentTracePhase,
	AgentWorkflowProgressEvent,
	AgentWorkflowProgressHandler,
	AgentWorkflowTrace,
	ApprovalRequirement,
	CompactAgentCommitOptions,
	CompactAgentCommitResult,
	CompactAgentPlanOptions,
	CompactAgentPlanResult,
	CompactAgentPostWriteVerification,
	CompactAgentPreview,
	CompactAgentTraceSummary,
	CompactApplySummary,
	CompactCheckSummary,
	CompactLintSummary,
	CompactLossAuditSummary,
	CompactPackageGraphAuditSummary,
	CompactRecalcSummary,
	CompactWritePlanSummary,
	CompactWritePolicySummary,
	LossAudit,
	LossAuditPackagePart,
	PackageActionKind,
	PackageActionProof,
	PackageActionProofCoverage,
	PackageActionProofEntry,
	PackageActionProofOptions,
	PackageGraphAudit,
	PreparedAgentPlan,
	ReleaseProofArtifactDigest,
	ReleaseProofBundle,
	ReleaseProofBundleOptions,
	ReleaseProofConsistencyCheck,
	ReleaseProofDiffEvidence,
	RepairAction,
	RepairPlanResult,
	WritePolicyDiagnostic,
	WritePolicyPackagePart,
	WritePolicyReport,
} from './agent-workflow.ts'
export {
	auditLossPolicy,
	auditPackageGraphIntegrity,
	auditPackageGraphRoundtrip,
	commitAgentPlan,
	commitAgentPlanFromWorkbook,
	compactAgentCommitResult,
	compactAgentPlanResult,
	createAgentCommitPackageActionProof,
	createAgentPlan,
	createAgentPlanFromWorkbook,
	createPackageActionProof,
	createPreparedAgentPlan,
	createReleaseProofBundle,
	createRepairPlan,
	digestPlan,
	sha256Bytes,
} from './agent-workflow.ts'
export type {
	CapabilityFilters,
	CapabilityPriority,
	CapabilityStatus,
	CapabilitySummary,
	CapabilitySurface,
	ExcelCapability,
} from './capabilities.ts'
export {
	EXCEL_CAPABILITIES,
	getCapability,
	isCapabilityGap,
	listCapabilities,
	summarizeCapabilities,
} from './capabilities.ts'
export type { ExportFormat, FormatDisplayOptions } from './format-helpers.ts'
/** Helpers for formatting cell values and inferring export formats. */
export {
	ensureOutputExtension,
	escapeDelimitedCell,
	formatDisplayCellValue,
	formatStyledDisplayCellValue,
	inferExportFormat,
	normalizeExportFormat,
	toA1Ref,
} from './format-helpers.ts'
export type {
	CycleReferenceResult,
	FormulaAssistOptions,
	FormulaAssistResult,
	FormulaBindingRole,
	FormulaBindingRoleKind,
	FormulaCodeAction,
	FormulaCodeActionOptions,
	FormulaDiagnostic,
	FormulaDiagnosticsResult,
	FormulaFunctionCompletion,
	FormulaFunctionCompletionOptions,
	FormulaFunctionSignature,
	FormulaFunctionSignatureHelp,
	FormulaHoverInfo,
	FormulaHoverKind,
	FormulaPrepareRenameBlockReason,
	FormulaPrepareRenameRange,
	FormulaPrepareRenameResult,
	FormulaReferenceRange,
	FormulaSignatureParameter,
	FormulaTokenClass,
	FormulaTokenRange,
	InsertFormulaReferenceOptions,
	InsertFormulaReferenceResult,
} from './formula-edit.ts'
export {
	cycleFormulaReferenceMode,
	formulaAssist,
	formulaBindingRoles,
	formulaCodeActions,
	formulaDiagnostics,
	formulaFunctionCompletions,
	formulaFunctionSignature,
	formulaFunctionSignatureHelp,
	formulaHover,
	formulaPrepareRename,
	formulaReferenceRanges,
	formulaTokenRanges,
	insertFormulaReference,
	referenceAtCursor,
} from './formula-edit.ts'
export type { CellInputParseOptions, ParsedCellInput } from './input-parser.ts'
export { parseCellInput, parseCellInputOperation } from './input-parser.ts'
export type {
	MutationJournal,
	MutationJournalAutoFilterPreimage,
	MutationJournalCellPreimage,
	MutationJournalCommentPreimage,
	MutationJournalConditionalFormatPreimage,
	MutationJournalDataValidationPreimage,
	MutationJournalDefinedNamePreimage,
	MutationJournalEntry,
	MutationJournalHyperlinkPreimage,
	MutationJournalIssue,
	MutationJournalMergePreimage,
	MutationJournalPanePreimage,
	MutationJournalPreimage,
	MutationJournalReasonCode,
	MutationJournalStructuralPreimage,
	MutationJournalStructuredIssue,
	MutationJournalSurface,
	MutationJournalTableColumnPreimage,
	MutationJournalTablePreimage,
	MutationJournalTableRenamePreimage,
	MutationJournalTableStylePreimage,
} from './journal.ts'
export {
	MUTATION_JOURNAL_ISSUE_CODES,
	MUTATION_JOURNAL_ISSUE_SCHEMA,
	MUTATION_JOURNAL_ISSUE_SCHEMA_VERSION,
	MUTATION_JOURNAL_REASON_CODES,
	MUTATION_JOURNAL_REASON_DESCRIPTIONS,
	MUTATION_JOURNAL_SURFACES,
	structureMutationJournalIssue,
} from './journal.ts'
export type {
	InspectWorkbookOpenPlanOptions,
	WorkbookOpenCostClass,
	WorkbookOpenFeatureCategory,
	WorkbookOpenFeatureSignal,
	WorkbookOpenIntent,
	WorkbookOpenPlan,
} from './open-plan.ts'
export { inspectWorkbookOpenPlan, planWorkbookOpen } from './open-plan.ts'
export type {
	OperationInputShape,
	OperationInputSource,
	PathMutationCompiler,
	ResolvedOperationInput,
} from './operation-input.ts'
export {
	compilePathMutationInput,
	resolveOperationInputForWorkbook,
	resolveOperationInputShape,
	withPathMutationResult,
} from './operation-input.ts'
export type {
	OperationApprovalMetadata,
	OperationInvalidExample,
	OperationJsonSchema,
	OperationSchema,
	ParseOperationsResult,
} from './ops.ts'
/** Typed operation builders and introspection. */
export * as ops from './ops.ts'
/** List all supported patch operations or generate JSON-schema-style descriptors for agents. */
export {
	getOperationsSchema,
	listOperations,
	operationValidationDetails,
	parseOperations,
} from './ops.ts'
export {
	compilePathMutations,
	SUPPORTED_PATH_MUTATION_ROOTS,
	SUPPORTED_PATH_MUTATION_SHAPES,
} from './path-mutations.ts'
export type {
	PreparedPathMutationPlanHandleOptions,
	PreparedPlanHandle,
	PreparedPlanMetadata,
	PreparedPlanStoreOptions,
	PreparedPlanTakeResult,
	PreparedPlanUnavailableReason,
} from './prepared-plan-store.ts'
export {
	PreparedPlanStore,
	preparedPathMutationPlanHandle,
	preparedPlanHandle,
	preparedPlanUnavailableError,
	withPreparedPlanHandle,
} from './prepared-plan-store.ts'
export { inspectRawPackagePart } from './raw-package.ts'
/** Base class for read-only workbook views (inspect, read, formula, check, lint, trace, diff). */
export { WorkbookReadView } from './read-view.ts'
export type {
	/** A cell selector: `"Sheet1!A1"`, `{ sheet: "Sheet1", ref: "A1" }`, or `{ sheet: "Sheet1", row: 0, col: 0 }`. */
	CellSelector,
	CellSelectorObject,
	/** A range selector: `"Sheet1!A1:B10"` or `{ sheet: "Sheet1", range: "A1:B10" }`. */
	RangeSelector,
	RangeSelectorObject,
} from './ref-selectors.ts'
export type {
	AscendSessionApplyOptions,
	AscendSessionApplyResult,
	AscendSessionApplyTimings,
	AscendSessionEditReadiness,
	AscendSessionOpenOptions,
	AscendSessionPrepareEditsResult,
	InteractiveUiRangeRequest,
	InteractiveUiRangeResult,
	InteractiveViewportCell,
	InteractiveViewportLayoutEntry,
	InteractiveViewportPatch,
	InteractiveViewportPatchInvalidation,
	InteractiveViewportPatchInvalidationReason,
	InteractiveViewportPatchResult,
	InteractiveViewportRequest,
	InteractiveViewportResult,
	SessionCacheOptions,
	WorkbookFirstWindowOptions,
	WorkbookFirstWindowResult,
	WorkbookLoadOptions,
	WorkbookSessionFirstWindowResult,
	WorkbookSessionOpenOptions,
} from './session.ts'
/** Cache and session management for multi-request read-only workbook access. */
export {
	AscendSession,
	configureSessionCache,
	interactiveViewportSnapshotKey,
	mergeInteractiveViewportPatch,
	WorkbookDocument,
	WorkbookSession,
} from './session.ts'
export type { SheetMetadataQueryOptions } from './sheet-handle.ts'
/** Fluent handle for reading/writing a single sheet inside an `AscendWorkbook`. */
export { SheetHandle } from './sheet-handle.ts'
export type { WorkbookRowStreamSource } from './stream.ts'
/** Stream workbook rows one chunk at a time for large-file processing. */
export { streamWorkbookRows } from './stream.ts'
/** Handle for structured table operations (read rows/columns, append). */
export { TableHandle } from './table-handle.ts'
export type {
	ActiveContentInfo,
	ActiveContentKind,
	AgentColumnSummary,
	AgentFormulaPatternInfo,
	AgentReadOptions,
	AgentSampleRow,
	AgentViewBudgetInfo,
	AgentViewOptions,
	AgentViewResult,
	ApplyAndRecalcResult,
	ApplyResult,
	BatchResult,
	CellFormulaReferenceInfo,
	CellInfo,
	ChangedCell,
	CheckIssue,
	CheckResult,
	CommentSummary,
	CompactCellInfo,
	CompactRangeChangeInvalidation,
	CompactRangeChangeInvalidationReason,
	CompactRangeInfo,
	CompactRangeWindowInfo,
	CompoundFormulaReferenceInfo,
	ConditionalFormatRuleSummary,
	DataValidationSummary,
	DefinedNameInfo,
	DirtyRegion,
	DumpBatchOptions,
	DumpBatchResult,
	DumpBatchUnsupportedCell,
	FlatCellValue,
	FormulaBindingSummary,
	FormulaCellEntry,
	FormulaInfo,
	FormulaReferenceInfo,
	FormulaReferenceScope,
	GetPivotDataFilter,
	GetPivotDataMatchInfo,
	GetPivotDataOutputInfo,
	GetPivotDataQuery,
	GetPivotDataResult,
	HyperlinkSummary,
	ImplicitIntersectionFormulaReferenceInfo,
	LintResult,
	LintWarning,
	MergeRangeSummary,
	NameFormulaReferenceInfo,
	PageMetadataSummary,
	PathMutation,
	PathMutationIssue,
	PathMutationPath,
	PathMutationResult,
	PivotAreaInfo,
	PivotAreaReferenceInfo,
	PivotAxisFieldItemInfo,
	PivotAxisItemInfo,
	PivotCacheDecodedValueInfo,
	PivotCacheFieldGroupDiscreteItemInfo,
	PivotCacheFieldGroupInfo,
	PivotCacheFieldGroupRangeInfo,
	PivotCacheFieldInfo,
	PivotCacheInfo,
	PivotCacheMaterializedRowInfo,
	PivotCacheRecordInfo,
	PivotCacheRecordsInfo,
	PivotCacheRecordValueInfo,
	PivotCacheRecordValueKind,
	PivotCacheRecordValueKindCount,
	PivotCacheRowsOptions,
	PivotCacheSharedItemsInfo,
	PivotChartFormatInfo,
	PivotDataFieldInfo,
	PivotFieldInfo,
	PivotFieldReference,
	PivotFormatInfo,
	PivotOutputAuditInfo,
	PivotOutputAuditMismatchInfo,
	PivotOutputAuditStatus,
	PivotOutputMaterializeMode,
	PivotOutputMaterializeOpsResult,
	PivotOutputMaterializeOptions,
	PivotOutputMaterializeResult,
	PivotOutputMaterializeUnsupportedInfo,
	PivotRefreshCacheRecordsInfo,
	PivotRefreshOutputState,
	PivotRefreshPlanInfo,
	PivotRefreshRecommendedOp,
	PivotRefreshTableInfo,
	PivotTableInfo,
	PivotTableLocationInfo,
	PivotTableOptionsInfo,
	PivotTableStyleInfo,
	PreviewResult,
	RangeAggregateInfo,
	RangeFormulaReferenceInfo,
	RangeInfo,
	RangeObjectsInfo,
	RangeRowsInfo,
	RangeWindowInfo,
	RawPackagePartInfo,
	RawPackagePartOptions,
	ReadSnapshotValidationResult,
	RecalcResult,
	SheetCommentInfo,
	SheetHyperlinkInfo,
	SheetInfo,
	SheetInspectInfo,
	SlicerCacheInfo,
	SlicerInfo,
	SpillFormulaReferenceInfo,
	StructuredFormulaReferenceInfo,
	TableInfo,
	TableRowInfo,
	TableWindowInfo,
	TemplateMergeOptions,
	TemplateMergePlaceholder,
	TemplateMergeResult,
	TemplateMergeUnsupportedCell,
	TemplateMergeValue,
	TimelineCacheInfo,
	TimelineInfo,
	TimelineRangeInfo,
	TimelineStateInfo,
	TraceNodeInfo,
	TraceResult,
	VisualFeatureCategory,
	VisualPackageFeatureInfo,
	WholeColumnFormulaReferenceInfo,
	WholeRowFormulaReferenceInfo,
	WorkbookGenerationInfo,
	WorkbookInfo,
	WorkbookLoadInfo,
	WorkbookReadSnapshotInfo,
	WorkbookViewInfo,
	WorkbookVisualInventoryInfo,
	WritePlanInfo,
} from './types.ts'
/**
 * `Ascend` — convenience entry point: `Ascend.open()`, `Ascend.create()`, `Ascend.fromCsv()`.
 *
 * `AscendWorkbook` — full mutable workbook for apply/recalc/save workflows.
 *
 * `BatchBuilder` — fluent builder for batching cell/formula/structural operations.
 */
export type { ApplyOptions, PreviewOptions, WorkbookBytesOptions } from './workbook.ts'
export { Ascend, AscendWorkbook, BatchBuilder } from './workbook.ts'
export type {
	WorkbookAgentContextPolicy,
	WorkbookTrustExecutionPolicy,
	WorkbookTrustFinding,
	WorkbookTrustFindingLocation,
	WorkbookTrustFindingSeverity,
	WorkbookTrustLevel,
	WorkbookTrustReport,
	WorkbookTrustReportOptions,
} from './workbook-trust.ts'
export { buildWorkbookTrustReport } from './workbook-trust.ts'
