export {
	type ActiveContentInfo,
	type ActiveContentKind,
	type ActiveXControlInfo,
	type CustomUiCallbackInfo,
	type CustomUiInfo,
	cloneActiveContentInfo,
	type FormControlInfo,
	type ShapeMacroInfo,
	type VbaModuleInfo,
	type VbaModuleKind,
	type VbaProjectInfo,
	type WorksheetControlInfo,
} from './active-content.ts'
export type { ChartPartInfo, ChartSeriesInfo, ChartSheetInfo } from './chart.ts'
export type { WorkbookConnectionPartInfo, WorkbookConnectionPartKind } from './connection.ts'
export type { WorkbookDataModelPartInfo, WorkbookDataModelPartKind } from './data-model.ts'
export type {
	DefinedName,
	DefinedNameAttribute,
	DefinedNameOptions,
	DefinedNameScope,
} from './defined-name.ts'
export { DefinedNameCollection } from './defined-name.ts'
export type {
	AutoFilter,
	CustomFilter,
	FilterColumn,
	FilterDateGroupItem,
	SortCondition,
	SortState,
} from './filter.ts'
export type { SheetId, StyleId, TableId, WorkbookId } from './ids.ts'
export { createSheetId, createTableId, createWorkbookId, DEFAULT_STYLE_ID } from './ids.ts'
export type {
	PivotAreaInfo,
	PivotAreaReferenceInfo,
	PivotAxisFieldItemInfo,
	PivotAxisItemInfo,
	PivotCacheFieldGroupDiscreteItemInfo,
	PivotCacheFieldGroupInfo,
	PivotCacheFieldGroupRangeInfo,
	PivotCacheFieldInfo,
	PivotCacheInfo,
	PivotCacheRecordInfo,
	PivotCacheRecordsInfo,
	PivotCacheRecordValueInfo,
	PivotCacheRecordValueKind,
	PivotCacheRecordValueKindCount,
	PivotCacheSharedItemInfo,
	PivotCacheSharedItemsInfo,
	PivotChartFormatInfo,
	PivotDataFieldInfo,
	PivotFieldInfo,
	PivotFieldItemInfo,
	PivotFieldReference,
	PivotFormatInfo,
	PivotTableInfo,
	PivotTableLocationInfo,
	PivotTableOptionsInfo,
	PivotTableStyleInfo,
	SlicerCacheInfo,
	SlicerCacheItemInfo,
	SlicerInfo,
	TimelineCacheInfo,
	TimelineInfo,
	TimelineRangeInfo,
	TimelineStateInfo,
} from './pivot.ts'
export {
	clonePivotCacheInfo,
	clonePivotTableInfo,
	normalizePivotCaption,
	pivotDataFieldCaptionsMatch,
} from './pivot.ts'
export { hashLegacyProtectionPassword, legacyProtectionPasswordMatches } from './protection.ts'
export { RangeIndex, type RangeIndexEntry, rangeMaskOffsets } from './range-index.ts'
export type { CellRef, RangeRef } from './refs.ts'
export {
	columnToIndex,
	expandRange,
	forEachCellInRange,
	indexToColumn,
	normalizeRange,
	parseA1,
	parseA1Safe,
	parseRange,
	parseSqref,
	rangeIntersection,
	rangeIntersects,
	sqrefIntersects,
	toA1,
	toRangeString,
} from './refs.ts'
export type {
	SheetAdvancedFilterInfo,
	SheetAnchorMarker,
	SheetBreak,
	SheetCellMetadataAttrs,
	SheetColDef,
	SheetComment,
	SheetCommentLegacyDrawing,
	SheetConditionalFormat,
	SheetConditionalFormatColor,
	SheetConditionalFormatColorScale,
	SheetConditionalFormatDataBar,
	SheetConditionalFormatIconSet,
	SheetConditionalFormatRule,
	SheetConditionalFormatValueObject,
	SheetDataValidation,
	SheetDrawingObjectKind,
	SheetDrawingObjectRef,
	SheetDrawingObjectRelationshipRef,
	SheetDrawingRefs,
	SheetFormatPr,
	SheetHeaderFooter,
	SheetHyperlink,
	SheetIgnoredError,
	SheetImageAnchor,
	SheetImageRef,
	SheetOutlinePr,
	SheetPageMargins,
	SheetPageSetup,
	SheetPageSetupPr,
	SheetPhoneticPr,
	SheetPrintOptions,
	SheetProtectedRange,
	SheetProtection,
	SheetRowDef,
	SheetSparklineGroupInfo,
	SheetSparklineInfo,
	SheetState,
	SheetTabColor,
	SheetThreadedComment,
	SheetView,
	SheetViewSelection,
	SheetViewType,
	SheetX14ConditionalFormatDataBarInfo,
	SheetX14ConditionalFormatIconInfo,
	SheetX14ConditionalFormatIconSetInfo,
	SheetX14ConditionalFormatInfo,
	SheetX14DataValidationInfo,
} from './sheet.ts'
export {
	cloneX14ConditionalFormatInfo,
	cloneX14DataValidationInfo,
	createSheet,
	Sheet,
} from './sheet.ts'

export type {
	ArrayFormulaInfo,
	Cell,
	CellFormulaBinding,
	DynamicArrayFormulaInfo,
	ExpectedDensity,
	SharedFormulaInfo,
} from './sparse-grid.ts'
export {
	SPARSE_GRID_CHUNK_SIZE,
	SPARSE_TO_DENSE_THRESHOLD,
	SparseGrid,
	type SparseGridStorageStats,
} from './sparse-grid.ts'
export type {
	AlignmentStyle,
	BorderEdge,
	BorderLineStyle,
	BorderStyle,
	CellStyle,
	Color,
	FillPattern,
	FillStyle,
	FontStyle,
	HorizontalAlign,
	VerticalAlign,
} from './style.ts'
export { cloneCellStyle } from './style-clone.ts'
export { cloneStyle, DEFAULT_STYLE, StyleRegistry } from './style-registry.ts'
export type {
	Table,
	TableColumn,
	TableQueryTableRef,
	TableStyleInfo,
	TableXmlColumnPr,
} from './table.ts'
export type {
	ExternalReferenceInfo,
	ExternalReferenceLinkBindingStatus,
	ExternalReferenceLinkRelationshipKind,
	NamedStyleInfo,
	WorkbookCoreDocumentProperties,
	WorkbookCustomDocumentProperty,
	WorkbookDocumentProperties,
	WorkbookDocumentPropertyAppValue,
	WorkbookDocumentPropertyScalar,
	WorkbookMacroSheetInfo,
	WorkbookPreservedMetadata,
	WorkbookPreservedSheetEntry,
	WorkbookPreservedStyles,
	WorkbookPreservedTheme,
	WorkbookPreservedXml,
	WorkbookProperties,
	WorkbookProtection,
	WorkbookStyleMetadata,
	WorkbookThemeColor,
	WorkbookThemeMetadata,
	WorkbookView,
} from './workbook.ts'
export { createWorkbook, Workbook } from './workbook.ts'
